import = [
	# "./catppuccin-mocha.toml"
	"./tokyo-night.toml"
]

[window.padding]
x = 8
y = 8

[window.dimensions]
columns = 80
lines = 25

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font]
size = 13

[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"
