import = [
	# "./catppuccin-mocha.toml"
	# "./tokyo-night.toml"
	"./rose-pine.toml"
]

# shell = "/usr/bin/tmux -u"
[shell]
program = "/usr/bin/tmux"
args = [ "-u" ]

# [window]
# opacity = 0.95

[window.padding]
x = 8
y = 8

[window.dimensions]
columns = 80
lines = 25

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font.bold]
family = "JetbrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono NF"
style = "Italic"

[font.normal]
family = "JetbrainsMono NF"
style = "Regular"

[font]
size = 13

[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"
